### ISSUE TITLE
Trace miss when generate trace for the program whose running output is a file

### ISSUE THREAD

**Issue by canxdy** [bstee615/trace-pintool#3]
The libtiff program produces a file with the input. The pin tool did not generate trace for the libtiff program.

At first, I did not use -o flag to get the output file. The output of the pin tool should be shown on the terminal. However, the terminal did not show the trace. I thought the issue might cause by the output of the pin tool was written into file with the output of the libtiff program. So I thought split output might solve the issue. Pin tool had -o flag which could get the output into a file. However, the issue still existed. The output file of the pin tool is empty. I tried to find the cause but I have not found out yet.

The attached folder includes a libtiff program which has the issue. The libtiff program is libtiff-2007-07-19-ce4b7af-7d6e298 of the manybug benchmark. The input I used for the pin tool is in input-generate-trace.txt.  And pin-trace.txt is the output file of the pin tool I got with -o flag.
[libtiff-withPinErrorOutput.zip](https://github.com/bstee615/trace-pintool/files/6079260/libtiff-withPinErrorOutput.zip)

**Comment by bstee615** [comment]
Thanks for the report!

Your test program `tiff2pdf` is a Bash script. Pin can only run on binary executables. You'll have to get the executable which is called by `tiff2pdf` and run that directly with Pin. I used `bash -x` to execute your command and echo each command and saw that it ends by calling into an executable `lt-tiff2pdf`, and when I ran this executable with Pin I got the attached trace.

To make the tool more transparent, I will look into adding a sanity check to assert that the program being run is a binary executable and has debug symbols.

```
$ bash -x libtiff/tools/tiff2pdf images/miniswhite-1c-1b.tiff > o-tiff2pdf.pdf
... Lots of output ...
+ exec /home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/.libs/lt-tiff2pdf images/miniswhite-1c-1b.tiff
lt-tiff2pdf: tif_dirinfo.c:291: _TIFFSetupFields: Assertion `tif->tif_fields != NULL' failed.
Aborted (core dumped)
$ ./libtiff/tools/.libs/lt-tiff2pdf images/miniswhite-1c-1b.tiff
II*lt-tiff2pdf: tif_dirinfo.c:291: _TIFFSetupFields: Assertion `tif->tif_fields != NULL' failed.
Aborted (core dumped)
$ ../../../../pin -t ../obj-intel64/trace.so -o pin-trace.txt -- ./libtiff/tools/.libs/lt-tiff2pdf images/miniswhite-1c-1b.tiff
II*lt-tiff2pdf: tif_dirinfo.c:291: _TIFFSetupFields: Assertion `tif->tif_fields != NULL' failed.
Aborted (core dumped)
$ head pin-trace.txt 
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:537
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:541
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:542
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:543
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:544
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:547
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:927
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/tools/tiff2pdf.c:929
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/libtiff/tif_unix.c:255
/home/benjis/work/tools/pin-3.17-98314-g0c048d619-gcc-linux/source/tools/trace-pintool/libtiff-withPinErrorOutput/libtiff/libtiff/tif_unix.c:25
```
